# Generated by Django 4.1.6 on 2023-03-31 04:58

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
